apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.name }}
  namespace: chou
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi