imageName: nginx
replicaCount: 1
namespace: chou

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  protocol: TCP

volumes:
  name: gp2-chou-argo
  claimName: gp2-chou-argo

initContainers:
  name: init-container
  image: busybox
